name: Deploy Github Pages

# 触发条件：在push到 hexo-blog-backup 分支后

on:
  push:
    branches:
      
      - hexo-blog-backup

env:
  TZ: Asia/Shanghai

# 任务
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Cache node Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-caches-${{ hashFiles('package-lock.json') }}
       
    - name: Install hexo dependencies
      run: |
        npm install hexo-cli -g
        npm install
        cd /themes/next @ 620b1e8
        npm install

    - name: Generate files
      run: |
        mv ./_config.theme.yml ./themes/next @ 620b1e8/_config.yml
        hexo generate



    - name: Deploy hexo blog
      uses: peaceiris/actions-gh-pages@v3
      with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: ${{ secrets.GH_REF }}
          publish_branch: master
          publish_dir: ./public
          full_commit_message: GitHub Actions Auto Builder
          disable_nojekyll: true