name: Deploy Github Pages

# 触发条件：在push到 hexo-blog-backup 分支后

on:
  push:
    branches:
      
      - hexo-blog-backup

env:
  TZ: Asia/Shanghai

# 任务
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Cache node Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-caches-${{ hashFiles('package-lock.json') }}
       
    - name: Install hexo dependencies
      run: |
        npm install hexo-cli -g
        npm install

    - name: Generate files
      run: |
        mv ./_config.theme.yml ./themes/next/_config.yml
        hexo generate



    - name: Deploy hexo blog
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "xufanxin86@gmail.com"
        git config --global user.name "jaheel"
        hexo d
        